// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WechatAccountInfo 微信账号信息
 */
export class WechatAccountInfo {
    /**
     * Creates a new WechatAccountInfo instance.
     * @param {Partial<WechatAccountInfo>} [$$source = {}] - The source object to create the WechatAccountInfo.
     */
    constructor($$source = {}) {
        if (!("wxid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wxid"] = "";
        }
        if (!("wxNum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wxNum"] = "";
        }
        if (!("nick" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nick"] = "";
        }
        if (!("avatarUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatarUrl"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["expireTime"] = undefined;
        }
        if (!("isExpire" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["isExpire"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WechatAccountInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WechatAccountInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WechatAccountInfo(/** @type {Partial<WechatAccountInfo>} */($$parsedSource));
    }
}
