// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAccounts 获取当前账号列表（供前端主动调用）
 * @returns {$CancellablePromise<$models.WechatAccountInfo[]>}
 */
export function GetAccounts() {
    return $Call.ByID(215267763).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetApp 设置 app 实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(566797270, app);
}

/**
 * StartWatching 开始监听文件变化并推送到前端
 * @returns {$CancellablePromise<void>}
 */
export function StartWatching() {
    return $Call.ByID(3550982490);
}

// Private type creation functions
const $$createType0 = $models.WechatAccountInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
