// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * 解除微信多开限制
 * @returns {$CancellablePromise<void>}
 */
export function EnableMultiWeChat() {
    return $Call.ByID(1062460666);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function RunWechat() {
    return $Call.ByID(1666666403);
}
