// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService 日志服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * SendLog 发送日志到前端
 * timeStamp: 时间戳，如 "2025-11-23 18:00:00"
 * response: 响应内容
 * logType: 日志类型（自定义字符串，如："群聊"、"私聊"、"注入成功"等）
 * msg: 日志消息
 * color: 显示颜色（如：#67C23A 绿色, #E6A23C 橙色, #F56C6C 红色, #409EFF 蓝色）
 * @param {string} timeStamp
 * @param {string} response
 * @param {string} logType
 * @param {string} msg
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function SendLog(timeStamp, response, logType, msg, color) {
    return $Call.ByID(507989589, timeStamp, response, logType, msg, color);
}

/**
 * SetApp 设置 app 实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3884551612, app);
}
