// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * 获取日志清理阈值
 * @returns {$CancellablePromise<number>}
 */
export function GetClearLog() {
    return $Call.ByID(1694295603);
}

/**
 * 获取配置文件微信配置信息
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetWechatConfig() {
    return $Call.ByID(178675830).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
