// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * 设置配置文件微信配置信息
 * @param {{ [_: string]: any }} obj
 * @returns {$CancellablePromise<boolean>}
 */
export function SetWechatConfig(obj) {
    return $Call.ByID(1959269774, obj);
}
