// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigGetService from "./configgetservice.js";
import * as ConfigSetService from "./configsetservice.js";
import * as ThemeService from "./themeservice.js";
export {
    ConfigGetService,
    ConfigSetService,
    ThemeService
};
