// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetTheme 获取当前主题设置
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(4293519692);
}

/**
 * 设置主题
 * theme: "light" (亮色主题), "dark" (黑色主题), "system" (跟随系统)
 * @param {string} theme
 * @returns {$CancellablePromise<boolean>}
 */
export function SetTheme(theme) {
    return $Call.ByID(3112045928, theme);
}
