// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {PluginMetadata}
             */
            this["metadata"] = (new PluginMetadata());
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("iconUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconUrl"] = "";
        }
        if (!("entryUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entryUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField0_0($$parsedSource["metadata"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

export class PluginMetadata {
    /**
     * Creates a new PluginMetadata instance.
     * @param {Partial<PluginMetadata>} [$$source = {}] - The source object to create the PluginMetadata.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginMetadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginMetadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginMetadata(/** @type {Partial<PluginMetadata>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PluginMetadata.createFrom;
