// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BroadcastEventToPlugins 向所有打开的插件广播事件
 * @param {string} eventType
 * @param {any} eventData
 * @returns {$CancellablePromise<void>}
 */
export function BroadcastEventToPlugins(eventType, eventData) {
    return $Call.ByID(1574995330, eventType, eventData);
}

/**
 * ClosePlugin 关闭插件窗口并清理引用
 * @param {string} pluginID
 * @returns {$CancellablePromise<void>}
 */
export function ClosePlugin(pluginID) {
    return $Call.ByID(686322313, pluginID);
}

/**
 * GetConfigYaml 获取 config.yaml 文件内容
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigYaml() {
    return $Call.ByID(2942042263);
}

/**
 * GetCurrentWechat 获取 currentWechat.json 文件内容
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentWechat() {
    return $Call.ByID(1701897585);
}

/**
 * OpenPlugin 在新窗口中打开插件
 * @param {string} pluginID
 * @returns {$CancellablePromise<void>}
 */
export function OpenPlugin(pluginID) {
    return $Call.ByID(4130989845, pluginID);
}

/**
 * RefreshPlugins 刷新插件列表（热重载）
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function RefreshPlugins() {
    return $Call.ByID(1853972487).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ScanPlugins 扫描插件（优先返回缓存）
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ScanPlugins() {
    return $Call.ByID(2692856413).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SendPluginLog 插件发送日志到主程序
 * @param {string} pluginID
 * @param {string} timeStamp
 * @param {string} response
 * @param {string} logType
 * @param {string} msg
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function SendPluginLog(pluginID, timeStamp, response, logType, msg, color) {
    return $Call.ByID(4007774371, pluginID, timeStamp, response, logType, msg, color);
}

/**
 * SetApp 设置应用实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(369351793, app);
}

/**
 * SetLogService 设置日志服务引用
 * @param {any} logService
 * @returns {$CancellablePromise<void>}
 */
export function SetLogService(logService) {
    return $Call.ByID(738644747, logService);
}

/**
 * UninstallPlugin 卸载插件
 * @param {string} pluginID
 * @returns {$CancellablePromise<void>}
 */
export function UninstallPlugin(pluginID) {
    return $Call.ByID(1649031799, pluginID);
}

/**
 * WriteFile 写入文件（用于前端上传）
 * 接收 Base64 编码的字符串，解决 Wails 二进制数据传输问题
 * @param {string} filePath
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(filePath, base64Data) {
    return $Call.ByID(3323196875, filePath, base64Data);
}

// Private type creation functions
const $$createType0 = $models.PluginInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
